export const productDataMocks = [
  {
    id: '1',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '05.07.2021',
    soldItems: 40,
    lastSale: '04.07.2021',
    price: 1010,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
  {
    id: '2',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '05.07.2021',
    soldItems: 40,
    lastSale: '04.07.2021',
    price: 1200,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
  {
    id: '3',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '05.07.2021',
    soldItems: 40,
    lastSale: '04.07.2021',
    price: 1300,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
  {
    id: '4',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '05.07.2021',
    soldItems: 40,
    lastSale: '05.07.2021',
    price: 1400,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
  {
    id: '5',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '05.07.2021',
    soldItems: 40,
    lastSale: '05.07.2021',
    price: 2000,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
  {
    id: '6',
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    productCategory: 'Sportswear',
    dateNow: '04.07.2021',
    soldItems: 100,
    lastSale: '05.07.2021',
    price: 5000,
    quantityGoods: '40',
    weightVolume: '5kg',
  },
]