export const productData = [
  {
    id: 1,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
  {
    id: 2,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
  {
    id: 3,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
  {
    id: 4,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
  {
    id: 5,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
  {
    id: 6,
    productName: 'Sneakers',
    store: 'Adidas',
    address: '15 Krylatskaya st...',
    category: 'Sportswear',
    creationDate: '05.07.2021',
    soldItems: '40',
    lastSale: '04.07.2021',
    price: '$1 000',
    remains: '40',
    weightVolume: '5kg',
  },
]